# Generated by Django 2.0.4 on 2018-04-16 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
